### ISSUE TITLE
Error: 401 Unauthorized - Invalid authorization

### ISSUE THREAD

**Issue by TesterVT** [Nerixyz/uploader#137]
I don't know what I'm doing, but the authorization field is filled in correctly in config.toml, secret is generated as written in the readme, but I constantly get this error

![Image](https://github.com/user-attachments/assets/fea55393-37d6-48c1-b619-470400eb2b0f)

**Comment by Nerixyz** [comment]
If your config looks like this:
```toml
bind = "127.0.0.1:4833"
file_dir = "uploads"
domain = "https://i.nerixyz.de"
authorization = "Bearer MyToken"
secret = "Something"
```
...then you need to enter exactly `Bearer MyToken` as the authorization in the frontend. Did you check that the request has exactly this authorization header?
